fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "soporte@uco.es"
        sender_name: "Área de Soporte y Atención al Usuario"
    service:
        mailer: fos_user.mailer.twig_swift