hwi_oauth:
    firewall_names: [main]
    fosub:
        properties:
            ssp: 'ssp_id'
    resource_owners:
        ssp:
            type: oauth2
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            access_token_url: 'https://identidad.uco.es/simplesaml/module.php/oauth2/access_token.php'
            authorization_url: 'https://identidad.uco.es/simplesaml/module.php/oauth2/authorize.php'
            infos_url: 'https://identidad.uco.es/simplesaml/module.php/oauth2/userinfo.php'
            scope: 'basic'
            user_response_class: 'HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse'
            paths:
                identifier: username
                nickname: 'attributes.uid.0'
                realname: 'attributes.commonName.0'
                email: 'attributes.mail.0'

services:
    my.oauth_aware.user_provider.service:
        class: App\Security\Core\User\FOSUBUserProvider
        arguments: [ '@fos_user.user_manager', { ssp: 'ssp_id' } ]
